### PR TITLE
Resolves DCP2-474: ArcLight - Bug: Titles in italics are cut off

### PR DESCRIPTION
**Pull request by gkostin1966**

### CODE REVIEW

**Comment by estelendur** [comment]
Do we have a test checking that a title with a unitdate in it will be indexed without the unitdate? Should we?

**Comment by cmkpowell** [comment]
@estelendur You mean like this one? 
<unittitle encodinganalog="245" type="main">HMS <emph render="italic">Braak</emph> Salvage collection <unitdate type="inclusive" era="ce" calendar="gregorian" encodinganalog="245$f">1888-1928</unitdate>
<unitdate type="bulk" era="ce" calendar="gregorian" encodinganalog="245$g">1888-1889</unitdate>

**Comment by estelendur** [comment]
@cmkpowell yah, like that one. (some of the code Greg changed is stuff I wrote while trying to fix "help, dates are wrong" in which I didn't entirely understand what I was doing. It looks like this code is a bit less spaghetti + more comprehension)

**Comment by gkostin1966** [comment]
bug_fix_italic_title
See modified sample data .../bhl/umich-bhl-032.xml for input.

**Review by respinos — APPROVED** [review]
More XPath! ❤️

**Pull request merged**
